
- name: Update 
  ansible.builtin.apt:
    update_cache: yes


- name: Install nginx
  apt:
    name: "{{package}}"
    state: "{{version}}"
  notify: my_handler
  changed_when: true

- name: template file
  template:
    src: ./index.html.j2
    dest: /var/www/html/index.html
